spring:
  application:
    name: NDPServer
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/fdp_shop_database
    username: root
    password: 123456xyz
  data:
    redis:
      port: 32772
      password: admin
      database: 0
      lettuce:
        pool:
          max-wait: 1000
  mail:
    username: 2037779479@qq.com
    password: wfmuoxwqaynscdfa
    port: 465
    host: smtp.qq.com
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          ssl:
            enable: true
  rabbitmq:
    port: 32773
    virtual-host: /
    username: admin
    password: admin
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
  global-config:
    db-config:
      id-type: auto
      update-strategy: not_null
      logic-delete-field: deleted
      logic-not-delete-value: 0
      logic-delete-value: 1
springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /index.html
    enabled: true
  packages-to-scan: com.slender.controller
  paths-to-match: /**
easy-es:
  address: 127.0.0.1:32768
